CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增长编码',
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `memo` VARCHAR(45) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;